export { default as Home } from './home'
export { default as ShoppingList } from './list'
export { default as Category } from './category'
export { default as Login } from './login'
export { default as Register } from './register'
